// const articles = [
//   {
//     img: "img/img1.PNG",
//     title: "Keep Your Stuff Alive",
//     data: "10 November 2084 by Tawana",
//     text: " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias,deleniti, id quibusdam aut optio saepe soluta tempore nequevoluptatum.",
//     order: "firstArticle",
//   },
//   {
//     img: "img/img2.PNG",
//     title: "A Love Letter to the City",
//     data: "2 November 2084 by Michael",
//     text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias, deleniti, id quibusdam aut optio saepe soluta tempore neque voluptatum.",
//     order: "secondArticle",
//   },
//   {
//     img: "img/img3.PNG",
//     title: "Design and Violence Debate",
//     data: "4 November 2084 by Tawana",
//     text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias, deleniti, id quibusdam aut optio saepe soluta tempore neque voluptatum.",
//     order: "thirdArticle",
//   },
//   {
//     img: "img/img4.PNG",
//     title: "Brigette Brown on Umbrellas",
//     data: "8 November 2084 by Christina",
//     text: ' Artcore is free HTML5 template by <span class="blue">template</span> <span class="green">mo</span>. There are total 12 HTML pages. Credit goes to <a class="orange blackLink" href="https://unsplash.com/"> Unsplash</a> for images.',
//     order: "fourthArticle",
//   },
//   {
//     img: "img/img5.PNG",
//     title: "The Night-Side of Hospitals",
//     data: "10 November 2084 by Tawana",
//     text: " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias,deleniti, id quibusdam aut optio saepe soluta tempore nequevoluptatum.",
//     order: "fifthArticle",
//   },
//   {
//     img: "img/img6.PNG",
//     title: "Porto Design Summer School",
//     data: "10 November 2084 by Tawana",
//     text: " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias,deleniti, id quibusdam aut optio saepe soluta tempore nequevoluptatum.",
//     order: "sixthArticle",
//   },
//   {
//     img: "img/img7.PNG",
//     title: "An Open Letter to Larry Page",
//     data: "6 November 2084 by Michael",
//     text: " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias,deleniti, id quibusdam aut optio saepe soluta tempore nequevoluptatum.",
//     order: "seventhArticle",
//   },
//   {
//     img: "img/img8.PNG",
//     title: "The Essence of a Teapot",
//     data: "31 October 2084 by George",
//     text: " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias,deleniti, id quibusdam aut optio saepe soluta tempore nequevoluptatum.",
//     order: "eighthArticle",
//   },
//   {
//     img: "img/img9.PNG",
//     title: "War of Streets and Houses",
//     data: "4 November 2084 by George",
//     text: " Lorem ipsum dolor sit amet, consectetur adipisicing elit. Alias,deleniti, id quibusdam aut optio saepe soluta tempore nequevoluptatum.",
//     order: "ninthArticle",
//   },
// ];
